### ISSUE TITLE
Phpstorm 2020.1 issue directory tree?

### ISSUE THREAD

**Issue by luukverhoeven** [pnbarx/idea-treecolor#1]
Thanks for this handy and cool plugin!
---

Is there an issue known in phpstorm 2020.1 that the colors not visible in the directory tree? 
It works on tabs and in the search dialog.

![afbeelding](https://user-images.githubusercontent.com/995760/80357654-962b5a80-887b-11ea-9687-562dffd70311.png)

```
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020

Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2022M
Cores: 32
Registry: ide.max.recent.projects=1000, run.processes.with.pty=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: mobi.hsz.idea.gitignore, zielu.gittoolbox, String Manipulation, com.steve.plugins.recentprojects, com.tobszarny.activetabhighlighter.plugin.id, com.ultrahob.zerolength.plugin, commit-template-idea-plugin, dev.pnbarx.idea.treecolor, tanvd.grazi, com.dmarcotte.handlebars, de.espend.idea.laravel, lv.midiana.misc.phpstorm-plugins.deep-keys, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, net.king2500.plugins.PhpAdvancedAutoComplete, org.psliwa.idea.composer, ru.adelf.idea.dotenv, com.wix.eslint, izhangzhihao.rainbow.brackets, ru.crazycoder.plugins.tabdir, some.awesome
```

**Comment by pnbarx** [comment]
It looks like you have disabled colors in Preferences -> Appearance & Behavior -> File Colors -> Enable File Colors. Please check this setting. Unfortunately, plugins can't highlight the project tree while this system setting is off. 

If changing the settings does not affect the issue, please let me know.

**Comment by luukverhoeven** [comment]
Thanks for your fast response, yes that did the trick. 👍
