### ISSUE TITLE
Options to support?

### ISSUE THREAD

**Issue by mallowigi** [pnbarx/idea-treecolor#10]
I really like this plugin, is there any way to support it?

**Comment by pnbarx** [comment]
Thank you for your feedback! This really motivates me to continue product development )
What did you mean about support?

**Comment by mallowigi** [comment]
I mean some GitHub sponsors or opencollective or ko-fi etc

**Comment by pnbarx** [comment]
I have PayPal: https://paypal.me/PavelBarykin

**Comment by pnbarx** [comment]
Thank you so much for your support! )
